version: '3'

services:
  nginx:
    image: nginx:1.15.1
    container_name: nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  keycloak:
     build: .
     restart: on-failure
     environment:
       - PROXY_ADDRESS_FORWARDING=true
     depends_on:
       - keycloak-db

  keycloak-db:
    image: postgres:10
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: